name: Deploy app to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "REACT_APP_API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV &&
          echo "REACT_APP_PRODUCTION_BASENAME=${{ secrets.PRODUCTION_BASENAME }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.13.5
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.18.0"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build app
        run: pnpm build
      - name: Deploy app to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
          cname: eluyema.github.io/courses-webapp-react
